name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Usar o token
        run: echo "Token: ${{ secrets.API_TOKEN }}"
        # OU passar para o código:
        # env:
        #   API_TOKEN: ${{ secrets.API_TOKEN }}
      
      - name: Rodar script com o token
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python meu_script.py